var qst1 = ["Qui est la petite soeur de Rarity ?",
						"Applejack",
						"Scootaloo",
						"Sweetie Belle",
						"Twilight Sparkle",
						3];
var qst2 = ["Qui veut détruire Ponyville et tout Equestria dans l'épisode 1 saison 1 ?",
						"Discord",
						"Nighmare Moon",
						"Zecora",
						"Queen Chrysalis",
						2];
var qst3 = ["Qui chante la toute première chanson ?",
						"Pinkie Pie",
						"Rainbow Dash",
						"Twilight Sparkle",
						"Fluttershy",
						1];
var qst4 = ["Comment s'appelle le lapin de Fluttershy ?",
						"Spike",
						"Angel",
						"Owlowiscious",
						"Gummy",
						2];
var qst5 = ["Qui porte l'élément de la loyauté ?",
					 "Fluttershy",
					 "Twilight Sparkle",
					 "Applejack",
					 "Rainbow Dash",
					 4];
var qst6 = ["De quelle espèce est Gummy ?",
					 "Chouette",
					 "Crocodile",
					 "Chien",
					 "Tortue",
					 2];
var qst7 = ["D'où vient Twilight Sparkle ?",
					 "Ponyville",
					 "The Crystal Empire",
					 "The Everfree Forest",
					 "Canterlot",
					 4];
var qst8 = ["Quel est le métier de Rarity ?",
					 "Tailleur",
					 "Fermier",
					 "Patissier",
					 "Chanteur",
					 1];
var qst9 = ["Qui ne fait pas partie des Cutie Mark Crusaders ?",
					 "Sweetie Belle",
					 "Apple Bloom",
					 "Diamond Tiara",
					 "Scootaloo",
					 3];
var qst10 = ["De quelle espèce est Gilda ?",
						"Alicorn",
						"Pegasus",
						"Unicorn",
						"Griffon",
						4];